export const data = [
  // Hydrogen
  {
    id: 1,
    element: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    atomicWeight: 1.008,
    group: 1,
    period: 1,
    block: 's',
    electronConfiguration: '1s1',
    electronegativity: 2.2,
    atomicRadius: 53,
    ionizationEnergy: 1312,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    density: 0.08988,
    yearDiscovered: 1766,
    discoveredBy: 'Henry Cavendish',
    description:
      'Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless gas at room temperature and is highly flammable. Hydrogen is essential for life and is a key component of water.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Hydrogen-2D-vdW.png/120px-Hydrogen-2D-vdW.png',
    color: '#FFFFFF',
    state: 'gas',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 1,
      neutrons: 0,
      electrons: 1,
      electronShells: [1],
    },

    uses: [
      'Fuel cells',
      'Rocket fuel',
      'Hydrogenation of fats and oils',
      'Production of ammonia',
    ],
  },
  // Helium
  {
    id: 2,
    element: 'He',
    name: 'Helium',
    atomicNumber: 2,
    atomicWeight: 4.0026,
    group: 18,
    period: 1,
    block: 's',
    electronConfiguration: '1s2',
    electronegativity: null,
    atomicRadius: 31,
    ionizationEnergy: 2372.3,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    density: 0.1786,
    yearDiscovered: 1868,
    discoveredBy: 'Pierre Janssen',
    description:
      'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas. It is the second lightest and second most abundant element in the observable universe.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Helium_atom_QM.svg/120px-Helium_atom_QM.svg.png',
    color: '#D9FFFF',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 2,
      neutrons: 2,
      electrons: 2,
      electronShells: [2],
    },
    uses: ['Cryogenics', 'Balloons', 'Airships', 'Protective gas in welding'],
    compounds: [],
  },
  // Lithium
  {
    id: 3,
    element: 'Li',
    name: 'Lithium',
    atomicNumber: 3,
    atomicWeight: 6.94,
    group: 1,
    period: 2,
    block: 's',
    electronConfiguration: '1s2 2s1',
    electronegativity: 0.98,
    atomicRadius: 167,
    ionizationEnergy: 520.2,
    meltingPoint: 453.65,
    boilingPoint: 1603,
    density: 0.534,
    yearDiscovered: 1817,
    discoveredBy: 'Johan August Arfwedson',
    description:
      'Lithium is a soft, silvery-white alkali metal. It is the lightest solid element and is highly reactive, especially in water.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Lithium_in_paraffin.jpg/120px-Lithium_in_paraffin.jpg',
    color: '#CC80FF',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 3,
      neutrons: 4,
      electrons: 3,
      electronShells: [2, 1],
    },
    uses: ['Rechargeable batteries', 'Mood-stabilizing drugs', 'Alloys'],
    compounds: [],
  },
  // Beryllium
  {
    id: 4,
    element: 'Be',
    name: 'Beryllium',
    atomicNumber: 4,
    atomicWeight: 9.0122,
    group: 2,
    period: 2,
    block: 's',
    electronConfiguration: '1s2 2s2',
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 899.5,
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    yearDiscovered: 1798,
    discoveredBy: 'Louis Nicolas Vauquelin',
    description:
      'Beryllium is a hard, grayish metal naturally found in mineral rocks, coal, soil, and volcanic dust.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Beryllium_%28Be%29.jpg/120px-Beryllium_%28Be%29.jpg',
    color: '#C2FF00',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 4,
      neutrons: 5,
      electrons: 4,
      electronShells: [2, 2],
    },
    uses: ['Aerospace materials', 'X-ray windows', 'Alloys'],
    compounds: [],
  },
  // Boron
  {
    id: 5,
    element: 'B',
    name: 'Boron',
    atomicNumber: 5,
    atomicWeight: 10.81,
    group: 13,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p1',
    electronegativity: 2.04,
    atomicRadius: 87,
    ionizationEnergy: 800.6,
    meltingPoint: 2349,
    boilingPoint: 4200,
    density: 2.34,
    yearDiscovered: 1808,
    discoveredBy: 'Joseph Louis Gay-Lussac',
    description:
      'Boron is a metalloid essential for plant growth and used in glass and detergents.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Boron.jpg/120px-Boron.jpg',
    color: '#FFB5B5',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 5,
      neutrons: 6,
      electrons: 5,
      electronShells: [2, 3],
    },
    uses: ['Glass production', 'Detergents', 'Semiconductors'],
    compounds: [],
  },
  // Carbon
  {
    id: 6,
    element: 'C',
    name: 'Carbon',
    atomicNumber: 6,
    atomicWeight: 12.011,
    group: 14,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p2',
    electronegativity: 2.55,
    atomicRadius: 67,
    ionizationEnergy: 1086.5,
    meltingPoint: 3823,
    boilingPoint: 4300,
    density: 2.267,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Carbon is a nonmetal, essential to all life, found in coal, graphite, and diamond.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Carbon_SG.jpg/120px-Carbon_SG.jpg',
    color: '#909090',
    state: 'solid',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 6,
      neutrons: 6,
      electrons: 6,
      electronShells: [2, 4],
    },
    uses: ['Steel', 'Filters', 'Pencils', 'Organic chemistry'],
    compounds: [],
  },
  // Nitrogen
  {
    id: 7,
    element: 'N',
    name: 'Nitrogen',
    atomicNumber: 7,
    atomicWeight: 14.007,
    group: 15,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p3',
    electronegativity: 3.04,
    atomicRadius: 56,
    ionizationEnergy: 1402.3,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    density: 1.2506,
    yearDiscovered: 1772,
    discoveredBy: 'Daniel Rutherford',
    description:
      'Nitrogen is a colorless, odorless gas making up 78% of Earth’s atmosphere.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Nitrogen_Spectra.jpg/120px-Nitrogen_Spectra.jpg',
    color: '#3050F8',
    state: 'gas',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 7,
      neutrons: 7,
      electrons: 7,
      electronShells: [2, 5],
    },
    uses: ['Fertilizers', 'Cryogenics', 'Atmosphere'],
    compounds: [],
  },
  // Oxygen
  {
    id: 8,
    element: 'O',
    name: 'Oxygen',
    atomicNumber: 8,
    atomicWeight: 15.999,
    group: 16,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p4',
    electronegativity: 3.44,
    atomicRadius: 48,
    ionizationEnergy: 1313.9,
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    density: 1.429,
    yearDiscovered: 1774,
    discoveredBy: 'Joseph Priestley',
    description:
      'Oxygen is a colorless, odorless gas essential for respiration and combustion.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Oxygen_discharge_tube.jpg/120px-Oxygen_discharge_tube.jpg',
    color: '#FF0D0D',
    state: 'gas',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 8,
      neutrons: 8,
      electrons: 8,
      electronShells: [2, 6],
    },
    uses: ['Breathing', 'Steelmaking', 'Water treatment'],
    compounds: [],
  },
  // Fluorine
  {
    id: 9,
    element: 'F',
    name: 'Fluorine',
    atomicNumber: 9,
    atomicWeight: 18.998,
    group: 17,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p5',
    electronegativity: 3.98,
    atomicRadius: 42,
    ionizationEnergy: 1681,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    density: 1.696,
    yearDiscovered: 1886,
    discoveredBy: 'Henri Moissan',
    description:
      'Fluorine is a pale yellow, highly reactive gas, the most electronegative element.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Fluorine_discharge_tube.jpg/120px-Fluorine_discharge_tube.jpg',
    color: '#FFFF30',
    state: 'gas',
    classification: 'halogen',
    atomicStructure: {
      protons: 9,
      neutrons: 10,
      electrons: 9,
      electronShells: [2, 7],
    },
    uses: ['Toothpaste', 'Teflon', 'Refrigerants'],
    compounds: [],
  },
  // Neon
  {
    id: 10,
    element: 'Ne',
    name: 'Neon',
    atomicNumber: 10,
    atomicWeight: 20.18,
    group: 18,
    period: 2,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6',
    electronegativity: null,
    atomicRadius: 38,
    ionizationEnergy: 2080.7,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    density: 0.9002,
    yearDiscovered: 1898,
    discoveredBy: 'Morris Travers',
    description:
      'Neon is a noble gas used in advertising signs and high-voltage indicators.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Neon_discharge_tube.jpg/120px-Neon_discharge_tube.jpg',
    color: '#B3E3F5',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 10,
      neutrons: 10,
      electrons: 10,
      electronShells: [2, 8],
    },
    uses: ['Neon signs', 'High-voltage indicators'],
    compounds: [],
  },
  // Sodium
  {
    id: 11,
    element: 'Na',
    name: 'Sodium',
    atomicNumber: 11,
    atomicWeight: 22.99,
    group: 1,
    period: 3,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s1',
    electronegativity: 0.93,
    atomicRadius: 190,
    ionizationEnergy: 495.8,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    density: 0.968,
    yearDiscovered: 1807,
    discoveredBy: 'Humphry Davy',
    description:
      'Sodium is a soft, silvery-white, highly reactive metal and a key component of table salt.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sodium_Science_Photo_Library.jpg/120px-Sodium_Science_Photo_Library.jpg',
    color: '#AB5CF2',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 11,
      neutrons: 12,
      electrons: 11,
      electronShells: [2, 8, 1],
    },
    uses: ['Table salt', 'Street lights', 'Soap making'],
    compounds: [],
  },
  // Magnesium
  {
    id: 12,
    element: 'Mg',
    name: 'Magnesium',
    atomicNumber: 12,
    atomicWeight: 24.305,
    group: 2,
    period: 3,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2',
    electronegativity: 1.31,
    atomicRadius: 145,
    ionizationEnergy: 737.7,
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    description:
      'Magnesium is a shiny gray solid, essential for life and used in alloys and fireworks.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Magnesium_crystals.jpg/120px-Magnesium_crystals.jpg',
    color: '#8AFF00',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 12,
      neutrons: 12,
      electrons: 12,
      electronShells: [2, 8, 2],
    },
    uses: ['Alloys', 'Fireworks', 'Health supplements'],
    compounds: [],
  },
  // Aluminum
  {
    id: 13,
    element: 'Al',
    name: 'Aluminum',
    atomicNumber: 13,
    atomicWeight: 26.982,
    group: 13,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p1',
    electronegativity: 1.61,
    atomicRadius: 118,
    ionizationEnergy: 577.5,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    density: 2.7,
    yearDiscovered: 1825,
    discoveredBy: 'Hans Christian Ørsted',
    description:
      'Aluminum is a lightweight, silvery-white metal used in cans, foil, and aircraft.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Aluminium-4.jpg/120px-Aluminium-4.jpg',
    color: '#BFA6A6',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 13,
      neutrons: 14,
      electrons: 13,
      electronShells: [2, 8, 3],
    },
    uses: ['Cans', 'Foil', 'Aircraft', 'Construction'],
    compounds: [],
  },
  // Silicon
  {
    id: 14,
    element: 'Si',
    name: 'Silicon',
    atomicNumber: 14,
    atomicWeight: 28.085,
    group: 14,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p2',
    electronegativity: 1.9,
    atomicRadius: 111,
    ionizationEnergy: 786.5,
    meltingPoint: 1687,
    boilingPoint: 3538,
    density: 2.3296,
    yearDiscovered: 1824,
    discoveredBy: 'Jöns Jacob Berzelius',
    description:
      'Silicon is a metalloid used in semiconductors, glass, and concrete.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Silicon.jpg/120px-Silicon.jpg',
    color: '#F0C8A0',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 14,
      neutrons: 14,
      electrons: 14,
      electronShells: [2, 8, 4],
    },
    uses: ['Semiconductors', 'Glass', 'Concrete'],
    compounds: [],
  },
  // Phosphorus
  {
    id: 15,
    element: 'P',
    name: 'Phosphorus',
    atomicNumber: 15,
    atomicWeight: 30.974,
    group: 15,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p3',
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 1011.8,
    meltingPoint: 317.3,
    boilingPoint: 553.7,
    density: 1.823,
    yearDiscovered: 1669,
    discoveredBy: 'Hennig Brand',
    description:
      'Phosphorus is a reactive nonmetal essential for life, used in fertilizers and matches.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Phosphorus-sample.jpg/120px-Phosphorus-sample.jpg',
    color: '#FF8000',
    state: 'solid',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 15,
      neutrons: 16,
      electrons: 15,
      electronShells: [2, 8, 5],
    },
    uses: ['Fertilizers', 'Matches', 'Detergents'],
    compounds: [],
  },
  // Sulfur
  {
    id: 16,
    element: 'S',
    name: 'Sulfur',
    atomicNumber: 16,
    atomicWeight: 32.06,
    group: 16,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p4',
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 999.6,
    meltingPoint: 388.36,
    boilingPoint: 717.8,
    density: 2.067,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Sulfur is a yellow nonmetal used in sulfuric acid, fertilizers, and vulcanized rubber.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Sulfur-sample.jpg/120px-Sulfur-sample.jpg',
    color: '#FFFF30',
    state: 'solid',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 16,
      neutrons: 16,
      electrons: 16,
      electronShells: [2, 8, 6],
    },
    uses: ['Fertilizers', 'Sulfuric acid', 'Rubber'],
    compounds: [],
  },
  // Chlorine
  {
    id: 17,
    element: 'Cl',
    name: 'Chlorine',
    atomicNumber: 17,
    atomicWeight: 35.45,
    group: 17,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p5',
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 1251.2,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    density: 3.214,
    yearDiscovered: 1774,
    discoveredBy: 'Carl Wilhelm Scheele',
    description:
      'Chlorine is a greenish-yellow gas used in disinfectants, bleach, and PVC.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Chlorine-sample.jpg/120px-Chlorine-sample.jpg',
    color: '#1FF01F',
    state: 'gas',
    classification: 'halogen',
    atomicStructure: {
      protons: 17,
      neutrons: 18,
      electrons: 17,
      electronShells: [2, 8, 7],
    },
    uses: ['Disinfectants', 'Bleach', 'PVC'],
    compounds: [],
  },
  // Argon
  {
    id: 18,
    element: 'Ar',
    name: 'Argon',
    atomicNumber: 18,
    atomicWeight: 39.948,
    group: 18,
    period: 3,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6',
    electronegativity: null,
    atomicRadius: 71,
    ionizationEnergy: 1520.6,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
    density: 1.784,
    yearDiscovered: 1894,
    discoveredBy: 'Lord Rayleigh',
    description:
      'Argon is a colorless, odorless noble gas used in lighting and welding.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Argon_discharge_tube.jpg/120px-Argon_discharge_tube.jpg',
    color: '#80D1E3',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 18,
      neutrons: 22,
      electrons: 18,
      electronShells: [2, 8, 8],
    },
    uses: ['Lighting', 'Welding', 'Insulation'],
    compounds: [],
  },
  // Potassium
  {
    id: 19,
    element: 'K',
    name: 'Potassium',
    atomicNumber: 19,
    atomicWeight: 39.098,
    group: 1,
    period: 4,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s1',
    electronegativity: 0.82,
    atomicRadius: 243,
    ionizationEnergy: 418.8,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    density: 0.862,
    yearDiscovered: 1807,
    discoveredBy: 'Humphry Davy',
    description:
      'Potassium is a soft, silvery metal essential for life, used in fertilizers and salt substitutes.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Potassium.jpg/120px-Potassium.jpg',
    color: '#8F40D4',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 19,
      neutrons: 20,
      electrons: 19,
      electronShells: [2, 8, 8, 1],
    },
    uses: ['Fertilizers', 'Salt substitutes', 'Fireworks'],
    compounds: [],
  },
  // Calcium
  {
    id: 20,
    element: 'Ca',
    name: 'Calcium',
    atomicNumber: 20,
    atomicWeight: 40.078,
    group: 2,
    period: 4,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2',
    electronegativity: 1.0,
    atomicRadius: 194,
    ionizationEnergy: 589.8,
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.54,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    description:
      'Calcium is a soft gray metal, essential for bones and teeth, used in cement and steel.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg/120px-Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg',
    color: '#3DFF00',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 20,
      neutrons: 20,
      electrons: 20,
      electronShells: [2, 8, 8, 2],
    },
    uses: ['Cement', 'Steel', 'Bones and teeth'],
    compounds: [],
  },
  // Scandium
  {
    id: 21,
    element: 'Sc',
    name: 'Scandium',
    atomicNumber: 21,
    atomicWeight: 44.956,
    group: 3,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d1',
    electronegativity: 1.36,
    atomicRadius: 184,
    ionizationEnergy: 633.1,
    meltingPoint: 1814,
    boilingPoint: 3109,
    density: 2.985,
    yearDiscovered: 1879,
    discoveredBy: 'Lars Fredrik Nilson',
    description:
      'Scandium is a soft, silvery metal used in aerospace components and sports equipment.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Scandium_crystals.jpg/120px-Scandium_crystals.jpg',
    color: '#E6E6E6',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 21,
      neutrons: 24,
      electrons: 21,
      electronShells: [2, 8, 9, 2],
    },
    uses: ['Aerospace', 'Sports equipment'],
    compounds: [],
  },
  // Titanium
  {
    id: 22,
    element: 'Ti',
    name: 'Titanium',
    atomicNumber: 22,
    atomicWeight: 47.867,
    group: 4,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d2',
    electronegativity: 1.54,
    atomicRadius: 176,
    ionizationEnergy: 658.8,
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.506,
    yearDiscovered: 1791,
    discoveredBy: 'William Gregor',
    description:
      'Titanium is a strong, corrosion-resistant metal used in aerospace, medical implants, and pigments.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Titanium_crystals.jpg/120px-Titanium_crystals.jpg',
    color: '#BFC2C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 22,
      neutrons: 26,
      electrons: 22,
      electronShells: [2, 8, 10, 2],
    },
    uses: ['Aerospace', 'Medical implants', 'Pigments'],
    compounds: [],
  },
  // Vanadium
  {
    id: 23,
    element: 'V',
    name: 'Vanadium',
    atomicNumber: 23,
    atomicWeight: 50.942,
    group: 5,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d3',
    electronegativity: 1.63,
    atomicRadius: 171,
    ionizationEnergy: 650.9,
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6.11,
    yearDiscovered: 1801,
    discoveredBy: 'Andrés Manuel del Río',
    description:
      'Vanadium is a hard, silvery-grey metal used to strengthen steel and in catalysts.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Vanadium_crystals.jpg/120px-Vanadium_crystals.jpg',
    color: '#A6A6AB',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 23,
      neutrons: 28,
      electrons: 23,
      electronShells: [2, 8, 11, 2],
    },
    uses: ['Steel alloys', 'Catalysts'],
    compounds: [],
  },
  // Chromium
  {
    id: 24,
    element: 'Cr',
    name: 'Chromium',
    atomicNumber: 24,
    atomicWeight: 51.996,
    group: 6,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s1 3d5',
    electronegativity: 1.66,
    atomicRadius: 166,
    ionizationEnergy: 652.9,
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.19,
    yearDiscovered: 1797,
    discoveredBy: 'Louis Nicolas Vauquelin',
    description:
      'Chromium is a hard, lustrous metal used in stainless steel and chrome plating.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Chromium_crystals.jpg/120px-Chromium_crystals.jpg',
    color: '#8A99C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 24,
      neutrons: 28,
      electrons: 24,
      electronShells: [2, 8, 13, 1],
    },
    uses: ['Stainless steel', 'Chrome plating'],
    compounds: [],
  },
  // Manganese
  {
    id: 25,
    element: 'Mn',
    name: 'Manganese',
    atomicNumber: 25,
    atomicWeight: 54.938,
    group: 7,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d5',
    electronegativity: 1.55,
    atomicRadius: 161,
    ionizationEnergy: 717.3,
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.21,
    yearDiscovered: 1774,
    discoveredBy: 'Johan Gottlieb Gahn',
    description:
      'Manganese is a hard, brittle metal used in steel production and batteries.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Manganese_element.jpg/120px-Manganese_element.jpg',
    color: '#9C7AC7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 25,
      neutrons: 30,
      electrons: 25,
      electronShells: [2, 8, 13, 2],
    },
    uses: ['Steel production', 'Batteries'],
    compounds: [],
  },
  // Iron
  {
    id: 26,
    element: 'Fe',
    name: 'Iron',
    atomicNumber: 26,
    atomicWeight: 55.845,
    group: 8,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d6',
    electronegativity: 1.83,
    atomicRadius: 156,
    ionizationEnergy: 762.5,
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Iron is a metal used in construction, tools, and is the main component of steel.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Iron_electrolytic_and_1cm3_cube.jpg/120px-Iron_electrolytic_and_1cm3_cube.jpg',
    color: '#E06633',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 26,
      neutrons: 30,
      electrons: 26,
      electronShells: [2, 8, 14, 2],
    },
    uses: ['Steel', 'Construction', 'Tools'],
    compounds: [],
  },
  // Cobalt
  {
    id: 27,
    element: 'Co',
    name: 'Cobalt',
    atomicNumber: 27,
    atomicWeight: 58.933,
    group: 9,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d7',
    electronegativity: 1.88,
    atomicRadius: 152,
    ionizationEnergy: 760.4,
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.86,
    yearDiscovered: 1735,
    discoveredBy: 'Georg Brandt',
    description:
      'Cobalt is a hard, lustrous metal used in batteries, magnets, and blue pigments.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Cobalt-2.jpg/120px-Cobalt-2.jpg',
    color: '#F090A0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 27,
      neutrons: 32,
      electrons: 27,
      electronShells: [2, 8, 15, 2],
    },
    uses: ['Batteries', 'Magnets', 'Pigments'],
    compounds: [],
  },
  // Nickel
  {
    id: 28,
    element: 'Ni',
    name: 'Nickel',
    atomicNumber: 28,
    atomicWeight: 58.693,
    group: 10,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d8',
    electronegativity: 1.91,
    atomicRadius: 149,
    ionizationEnergy: 737.1,
    meltingPoint: 1728,
    boilingPoint: 3186,
    density: 8.912,
    yearDiscovered: 1751,
    discoveredBy: 'Axel Fredrik Cronstedt',
    description:
      'Nickel is a silvery-white metal used in coins, stainless steel, and batteries.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nickel_chunk.jpg/120px-Nickel_chunk.jpg',
    color: '#50D050',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 28,
      neutrons: 31,
      electrons: 28,
      electronShells: [2, 8, 16, 2],
    },
    uses: ['Coins', 'Stainless steel', 'Batteries'],
    compounds: [],
  },
  // Copper
  {
    id: 29,
    element: 'Cu',
    name: 'Copper',
    atomicNumber: 29,
    atomicWeight: 63.546,
    group: 11,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s1 3d10',
    electronegativity: 1.9,
    atomicRadius: 145,
    ionizationEnergy: 745.5,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    density: 8.96,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Copper is a reddish metal used in electrical wiring, plumbing, and coins.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Copper_Sample.jpg/120px-Copper_Sample.jpg',
    color: '#C88033',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 29,
      neutrons: 35,
      electrons: 29,
      electronShells: [2, 8, 18, 1],
    },
    uses: ['Wiring', 'Plumbing', 'Coins'],
    compounds: [],
  },
  // Zinc
  {
    id: 30,
    element: 'Zn',
    name: 'Zinc',
    atomicNumber: 30,
    atomicWeight: 65.38,
    group: 12,
    period: 4,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10',
    electronegativity: 1.65,
    atomicRadius: 142,
    ionizationEnergy: 906.4,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    density: 7.134,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Zinc is a bluish-white metal used to galvanize steel and in batteries.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Zinc_fragment_sublimed_and_1cm3_cube.jpg/120px-Zinc_fragment_sublimed_and_1cm3_cube.jpg',
    color: '#7D80B0',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 30,
      neutrons: 35,
      electrons: 30,
      electronShells: [2, 8, 18, 2],
    },
    uses: ['Galvanizing', 'Batteries', 'Alloys'],
    compounds: [],
  },
  // Gallium
  {
    id: 31,
    element: 'Ga',
    name: 'Gallium',
    atomicNumber: 31,
    atomicWeight: 69.723,
    group: 13,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p1',
    electronegativity: 1.81,
    atomicRadius: 136,
    ionizationEnergy: 578.8,
    meltingPoint: 302.91,
    boilingPoint: 2477,
    density: 5.904,
    yearDiscovered: 1875,
    discoveredBy: 'Paul-Émile Lecoq de Boisbaudran',
    description:
      'Gallium is a soft metal that melts in your hand, used in electronics and LEDs.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Gallium_crystals.jpg/120px-Gallium_crystals.jpg',
    color: '#C28F8F',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 31,
      neutrons: 39,
      electrons: 31,
      electronShells: [2, 8, 18, 3],
    },
    uses: ['Electronics', 'LEDs', 'Thermometers'],
    compounds: [],
  },
  // Germanium
  {
    id: 32,
    element: 'Ge',
    name: 'Germanium',
    atomicNumber: 32,
    atomicWeight: 72.63,
    group: 14,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p2',
    electronegativity: 2.01,
    atomicRadius: 125,
    ionizationEnergy: 762,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    density: 5.323,
    yearDiscovered: 1886,
    discoveredBy: 'Clemens Winkler',
    description:
      'Germanium is a brittle metalloid used in semiconductors and fiber optics.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Germanium_crystal.jpg/120px-Germanium_crystal.jpg',
    color: '#668F8F',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 32,
      neutrons: 41,
      electrons: 32,
      electronShells: [2, 8, 18, 4],
    },
    uses: ['Semiconductors', 'Fiber optics'],
    compounds: [],
  },
  // Arsenic
  {
    id: 33,
    element: 'As',
    name: 'Arsenic',
    atomicNumber: 33,
    atomicWeight: 74.922,
    group: 15,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p3',
    electronegativity: 2.18,
    atomicRadius: 114,
    ionizationEnergy: 947,
    meltingPoint: 1090,
    boilingPoint: 887,
    density: 5.776,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Arsenic is a metalloid used in pesticides, alloys, and semiconductors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Arsenic-sample.jpg/120px-Arsenic-sample.jpg',
    color: '#BD80E3',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 33,
      neutrons: 42,
      electrons: 33,
      electronShells: [2, 8, 18, 5],
    },
    uses: ['Pesticides', 'Alloys', 'Semiconductors'],
    compounds: [],
  },
  // Selenium
  {
    id: 34,
    element: 'Se',
    name: 'Selenium',
    atomicNumber: 34,
    atomicWeight: 78.971,
    group: 16,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p4',
    electronegativity: 2.55,
    atomicRadius: 103,
    ionizationEnergy: 941,
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.809,
    yearDiscovered: 1817,
    discoveredBy: 'Jöns Jacob Berzelius',
    description:
      'Selenium is a nonmetal used in glassmaking, electronics, and as a dietary supplement.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Selenium_powder.jpg/120px-Selenium_powder.jpg',
    color: '#FFA100',
    state: 'solid',
    classification: 'nonmetal',
    atomicStructure: {
      protons: 34,
      neutrons: 45,
      electrons: 34,
      electronShells: [2, 8, 18, 6],
    },
    uses: ['Glassmaking', 'Electronics', 'Supplements'],
    compounds: [],
  },
  // Bromine
  {
    id: 35,
    element: 'Br',
    name: 'Bromine',
    atomicNumber: 35,
    atomicWeight: 79.904,
    group: 17,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5',
    electronegativity: 2.96,
    atomicRadius: 94,
    ionizationEnergy: 1139.9,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    density: 3.1028,
    yearDiscovered: 1826,
    discoveredBy: 'Antoine Jérôme Balard',
    description:
      'Bromine is a reddish-brown liquid at room temperature, used in flame retardants and photography.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Bromine-ampoule.jpg/120px-Bromine-ampoule.jpg',
    color: '#A62929',
    state: 'liquid',
    classification: 'halogen',
    atomicStructure: {
      protons: 35,
      neutrons: 45,
      electrons: 35,
      electronShells: [2, 8, 18, 7],
    },
    uses: ['Flame retardants', 'Photography', 'Water treatment'],
    compounds: [],
  },
  // Krypton
  {
    id: 36,
    element: 'Kr',
    name: 'Krypton',
    atomicNumber: 36,
    atomicWeight: 83.798,
    group: 18,
    period: 4,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6',
    electronegativity: null,
    atomicRadius: 83,
    ionizationEnergy: 1350.0,
    meltingPoint: 115.79,
    boilingPoint: 140.74,
    density: 3.733,
    yearDiscovered: 1898,
    discoveredBy: 'William Ramsay',
    description:
      'Krypton is a colorless, odorless noble gas used in high-performance lighting and photography.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Krypton_discharge_tube.jpg/120px-Krypton_discharge_tube.jpg',
    color: '#5C5CFF',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 36,
      neutrons: 48,
      electrons: 36,
      electronShells: [2, 8, 18, 8],
    },
    uses: ['High-performance lighting', 'Photography'],
    compounds: [],
  },
  // Rubidium
  {
    id: 37,
    element: 'Rb',
    name: 'Rubidium',
    atomicNumber: 37,
    atomicWeight: 85.4678,
    group: 1,
    period: 5,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s1',
    electronegativity: 0.82,
    atomicRadius: 248,
    ionizationEnergy: 403.0,
    meltingPoint: 39.31,
    boilingPoint: 688,
    density: 1.532,
    yearDiscovered: 1861,
    discoveredBy: 'Robert Bunsen',
    description:
      'Rubidium is a soft, silvery-white metallic element of the alkali metal group, used in fireworks and atomic clocks.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Rubidium_crystals.jpg/120px-Rubidium_crystals.jpg',
    color: '#A24AFC',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 37,
      neutrons: 48,
      electrons: 37,
      electronShells: [2, 8, 18, 8, 1],
    },
    uses: ['Fireworks', 'Atomic clocks'],
    compounds: [],
  },
  // Strontium
  {
    id: 38,
    element: 'Sr',
    name: 'Strontium',
    atomicNumber: 38,
    atomicWeight: 87.62,
    group: 2,
    period: 5,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2',
    electronegativity: 0.95,
    atomicRadius: 215,
    ionizationEnergy: 549.5,
    meltingPoint: 777,
    boilingPoint: 1382,
    density: 2.64,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    description:
      'Strontium is a soft, silvery-white metallic element, used in fireworks, flares, and as a getter in vacuum tubes.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Strontium_crystals.jpg/120px-Strontium_crystals.jpg',
    color: '#D7FFFF',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 38,
      neutrons: 50,
      electrons: 38,
      electronShells: [2, 8, 18, 8, 2],
    },
    uses: ['Fireworks', 'Flares', 'Getter in vacuum tubes'],
    compounds: [],
  },
  // Yttrium
  {
    id: 39,
    element: 'Y',
    name: 'Yttrium',
    atomicNumber: 39,
    atomicWeight: 88.905,
    group: 3,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d1',
    electronegativity: 1.22,
    atomicRadius: 210,
    ionizationEnergy: 600.0,
    meltingPoint: 1526,
    boilingPoint: 3337,
    density: 4.469,
    yearDiscovered: 1794,
    discoveredBy: 'Johan Gadolin',
    description:
      'Yttrium is a silvery-metallic element, used in LEDs, phosphors, and as a neutron moderator in nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Yttrium_crystals.jpg/120px-Yttrium_crystals.jpg',
    color: '#A6A6A6',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 39,
      neutrons: 50,
      electrons: 39,
      electronShells: [2, 8, 18, 9, 2],
    },
    uses: ['LEDs', 'Phosphors', 'Neutron moderator in nuclear reactors'],
    compounds: [],
  },
  // Zirconium
  {
    id: 40,
    element: 'Zr',
    name: 'Zirconium',
    atomicNumber: 40,
    atomicWeight: 91.224,
    group: 4,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d2',
    electronegativity: 1.33,
    atomicRadius: 175,
    ionizationEnergy: 640.0,
    meltingPoint: 1855,
    boilingPoint: 4377,
    density: 6.52,
    yearDiscovered: 1789,
    discoveredBy: 'Martin Heinrich Klaproth',
    description:
      'Zirconium is a strong, gray-white metal, used in nuclear reactors, spacecraft, and as a diamond substitute.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Zirconium_crystals.jpg/120px-Zirconium_crystals.jpg',
    color: '#BFC2C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 40,
      neutrons: 51,
      electrons: 40,
      electronShells: [2, 8, 18, 10, 2],
    },
    uses: ['Nuclear reactors', 'Spacecraft', 'Diamond substitute'],
    compounds: [],
  },
  // Niobium
  {
    id: 41,
    element: 'Nb',
    name: 'Niobium',
    atomicNumber: 41,
    atomicWeight: 92.906,
    group: 5,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d4',
    electronegativity: 1.6,
    atomicRadius: 146,
    ionizationEnergy: 745.0,
    meltingPoint: 2468,
    boilingPoint: 4744,
    density: 8.57,
    yearDiscovered: 1801,
    discoveredBy: 'Charles Hatchett',
    description:
      'Niobium is a soft, gray metal, used in superconducting materials, and as an alloying agent in steel.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Niobium_crystals.jpg/120px-Niobium_crystals.jpg',
    color: '#A6A6AB',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 41,
      neutrons: 51,
      electrons: 41,
      electronShells: [2, 8, 18, 12, 1],
    },
    uses: ['Superconducting materials', 'Alloying agent in steel'],
    compounds: [],
  },
  // Molybdenum
  {
    id: 42,
    element: 'Mo',
    name: 'Molybdenum',
    atomicNumber: 42,
    atomicWeight: 95.94,
    group: 6,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d5',
    electronegativity: 2.16,
    atomicRadius: 139,
    ionizationEnergy: 684.0,
    meltingPoint: 2623,
    boilingPoint: 4639,
    density: 10.28,
    yearDiscovered: 1778,
    discoveredBy: 'Carl Wilhelm Scheele',
    description:
      'Molybdenum is a silvery-white metal, used in steel alloys, and as a catalyst in the petroleum industry.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Molybdenum_crystals.jpg/120px-Molybdenum_crystals.jpg',
    color: '#BFBFBF',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 42,
      neutrons: 54,
      electrons: 42,
      electronShells: [2, 8, 18, 13, 1],
    },
    uses: ['Steel alloys', 'Catalyst in petroleum industry'],
    compounds: [],
  },
  // Technetium
  {
    id: 43,
    element: 'Tc',
    name: 'Technetium',
    atomicNumber: 43,
    atomicWeight: 98,
    group: 7,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d6',
    electronegativity: 1.9,
    atomicRadius: 139,
    ionizationEnergy: 702.0,
    meltingPoint: 2157,
    boilingPoint: 4265,
    density: 11.5,
    yearDiscovered: 1937,
    discoveredBy: 'Carlo Perrier and Emilio Segrè',
    description:
      'Technetium is a silvery-gray metal, used in radioactive tracers, and as a catalyst in organic synthesis.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Technetium_crystals.jpg/120px-Technetium_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 43,
      neutrons: 55,
      electrons: 43,
      electronShells: [2, 8, 18, 13, 2],
    },
    uses: ['Radioactive tracers', 'Catalyst in organic synthesis'],
    compounds: [],
  },
  // Ruthenium
  {
    id: 44,
    element: 'Ru',
    name: 'Ruthenium',
    atomicNumber: 44,
    atomicWeight: 101.07,
    group: 8,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d7',
    electronegativity: 2.2,
    atomicRadius: 139,
    ionizationEnergy: 710.0,
    meltingPoint: 2334,
    boilingPoint: 4150,
    density: 12.37,
    yearDiscovered: 1844,
    discoveredBy: 'Karl Ernst Claus',
    description:
      'Ruthenium is a rare, silvery-white metal, used in electrical contacts, and as a catalyst in chemical reactions.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ruthenium_crystals.jpg/120px-Ruthenium_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 44,
      neutrons: 57,
      electrons: 44,
      electronShells: [2, 8, 18, 13, 3],
    },
    uses: ['Electrical contacts', 'Catalyst in chemical reactions'],
    compounds: [],
  },
  // Rhodium
  {
    id: 45,
    element: 'Rh',
    name: 'Rhodium',
    atomicNumber: 45,
    atomicWeight: 102.905,
    group: 9,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d8',
    electronegativity: 2.28,
    atomicRadius: 139,
    ionizationEnergy: 740.0,
    meltingPoint: 1964,
    boilingPoint: 3727,
    density: 12.41,
    yearDiscovered: 1803,
    discoveredBy: 'William Hyde Wollaston',
    description:
      'Rhodium is a silvery-white, hard metal, used in catalytic converters, and as a mirror finish in jewelry.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Rhodium_crystals.jpg/120px-Rhodium_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 45,
      neutrons: 53,
      electrons: 45,
      electronShells: [2, 8, 18, 13, 4],
    },
    uses: ['Catalytic converters', 'Mirror finish in jewelry'],
    compounds: [],
  },
  // Palladium
  {
    id: 46,
    element: 'Pd',
    name: 'Palladium',
    atomicNumber: 46,
    atomicWeight: 106.42,
    group: 10,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10',
    electronegativity: 2.2,
    atomicRadius: 137,
    ionizationEnergy: 804.0,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    density: 12.03,
    yearDiscovered: 1803,
    discoveredBy: 'William Hyde Wollaston',
    description:
      'Palladium is a rare, silvery-white metal, used in catalytic converters, jewelry, and as an industrial catalyst.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Palladium_crystals.jpg/120px-Palladium_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 46,
      neutrons: 55,
      electrons: 46,
      electronShells: [2, 8, 18, 14, 2],
    },
    uses: ['Catalytic converters', 'Jewelry', 'Industrial catalyst'],
    compounds: [],
  },
  // Silver
  {
    id: 47,
    element: 'Ag',
    name: 'Silver',
    atomicNumber: 47,
    atomicWeight: 107.8682,
    group: 11,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10',
    electronegativity: 1.93,
    atomicRadius: 144,
    ionizationEnergy: 731.0,
    meltingPoint: 961.8,
    boilingPoint: 2162,
    density: 10.49,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Silver is a shiny, white metal, used in jewelry, coins, and as an industrial catalyst.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Silver_crystals.jpg/120px-Silver_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 47,
      neutrons: 61,
      electrons: 47,
      electronShells: [2, 8, 18, 18, 1],
    },
    uses: ['Jewelry', 'Coins', 'Industrial catalyst'],
    compounds: [],
  },
  // Cadmium
  {
    id: 48,
    element: 'Cd',
    name: 'Cadmium',
    atomicNumber: 48,
    atomicWeight: 112.414,
    group: 12,
    period: 5,
    block: 'd',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10',
    electronegativity: 1.69,
    atomicRadius: 151,
    ionizationEnergy: 867.0,
    meltingPoint: 321.07,
    boilingPoint: 765,
    density: 8.65,
    yearDiscovered: 1817,
    discoveredBy: 'Friedrich Strohmeyer',
    description:
      'Cadmium is a soft, bluish-white metal, used in batteries, pigments, and as a stabilizer in plastics.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Cadmium_crystals.jpg/120px-Cadmium_crystals.jpg',
    color: '#C0C0C0',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 48,
      neutrons: 64,
      electrons: 48,
      electronShells: [2, 8, 18, 18, 2],
    },
    uses: ['Batteries', 'Pigments', 'Stabilizer in plastics'],
    compounds: [],
  },
  // Indium
  {
    id: 49,
    element: 'In',
    name: 'Indium',
    atomicNumber: 49,
    atomicWeight: 114.818,
    group: 13,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p1',
    electronegativity: 1.78,
    atomicRadius: 167,
    ionizationEnergy: 558.3,
    meltingPoint: 429.75,
    boilingPoint: 2345,
    density: 7.31,
    yearDiscovered: 1863,
    discoveredBy: 'Ferdinand Reich',
    description:
      'Indium is a soft, silvery metal used in touchscreens, solders, and semiconductors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Indium-2.jpg/120px-Indium-2.jpg',
    color: '#A67573',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 49,
      neutrons: 66,
      electrons: 49,
      electronShells: [2, 8, 18, 18, 3],
    },
    uses: ['Touchscreens', 'Solders', 'Semiconductors'],
    compounds: [],
  },
  // Tin
  {
    id: 50,
    element: 'Sn',
    name: 'Tin',
    atomicNumber: 50,
    atomicWeight: 118.71,
    group: 14,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p2',
    electronegativity: 1.96,
    atomicRadius: 162,
    ionizationEnergy: 708.6,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    density: 7.287,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Tin is a malleable, silvery metal used in solder, tin plating, and alloys.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tin-2.jpg/120px-Tin-2.jpg',
    color: '#CCCCCC',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 50,
      neutrons: 69,
      electrons: 50,
      electronShells: [2, 8, 18, 18, 4],
    },
    uses: ['Solder', 'Tin plating', 'Alloys'],
    compounds: [],
  },
  // Antimony
  {
    id: 51,
    element: 'Sb',
    name: 'Antimony',
    atomicNumber: 51,
    atomicWeight: 121.76,
    group: 15,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p3',
    electronegativity: 2.05,
    atomicRadius: 141,
    ionizationEnergy: 834,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    density: 6.697,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Antimony is a lustrous gray metalloid used in flame retardants, alloys, and semiconductors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Antimony-4.jpg/120px-Antimony-4.jpg',
    color: '#9E63B5',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 51,
      neutrons: 71,
      electrons: 51,
      electronShells: [2, 8, 18, 18, 5],
    },
    uses: ['Flame retardants', 'Alloys', 'Semiconductors'],
    compounds: [],
  },
  // Tellurium
  {
    id: 52,
    element: 'Te',
    name: 'Tellurium',
    atomicNumber: 52,
    atomicWeight: 127.6,
    group: 16,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p4',
    electronegativity: 2.1,
    atomicRadius: 140,
    ionizationEnergy: 869.3,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    density: 6.24,
    yearDiscovered: 1782,
    discoveredBy: 'Franz-Joseph Müller von Reichenstein',
    description:
      'Tellurium is a brittle, silvery metalloid used in alloys and semiconductors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tellurium2.jpg/120px-Tellurium2.jpg',
    color: '#D47A00',
    state: 'solid',
    classification: 'metalloid',
    atomicStructure: {
      protons: 52,
      neutrons: 76,
      electrons: 52,
      electronShells: [2, 8, 18, 18, 6],
    },
    uses: ['Alloys', 'Semiconductors'],
    compounds: [],
  },
  // Iodine
  {
    id: 53,
    element: 'I',
    name: 'Iodine',
    atomicNumber: 53,
    atomicWeight: 126.904,
    group: 17,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p5',
    electronegativity: 2.66,
    atomicRadius: 133,
    ionizationEnergy: 1008.4,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    density: 4.93,
    yearDiscovered: 1811,
    discoveredBy: 'Bernard Courtois',
    description:
      'Iodine is a dark, lustrous solid that sublimes to a violet gas, used in medicine and photography.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Iodine-sample.jpg/120px-Iodine-sample.jpg',
    color: '#940094',
    state: 'solid',
    classification: 'halogen',
    atomicStructure: {
      protons: 53,
      neutrons: 74,
      electrons: 53,
      electronShells: [2, 8, 18, 18, 7],
    },
    uses: ['Medicine', 'Photography'],
    compounds: [],
  },
  // Xenon
  {
    id: 54,
    element: 'Xe',
    name: 'Xenon',
    atomicNumber: 54,
    atomicWeight: 131.293,
    group: 18,
    period: 5,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6',
    electronegativity: 2.6,
    atomicRadius: 108,
    ionizationEnergy: 1170.4,
    meltingPoint: 161.4,
    boilingPoint: 165.1,
    density: 5.894,
    yearDiscovered: 1898,
    discoveredBy: 'William Ramsay',
    description:
      'Xenon is a colorless, dense noble gas used in lighting and anesthesia.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Xenon_discharge_tube.jpg/120px-Xenon_discharge_tube.jpg',
    color: '#429EB0',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 54,
      neutrons: 77,
      electrons: 54,
      electronShells: [2, 8, 18, 18, 8],
    },
    uses: ['Lighting', 'Anesthesia'],
    compounds: [],
  },
  // Cesium
  {
    id: 55,
    element: 'Cs',
    name: 'Cesium',
    atomicNumber: 55,
    atomicWeight: 132.905,
    group: 1,
    period: 6,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s1',
    electronegativity: 0.79,
    atomicRadius: 265,
    ionizationEnergy: 375.7,
    meltingPoint: 301.7,
    boilingPoint: 944,
    density: 1.93,
    yearDiscovered: 1860,
    discoveredBy: 'Robert Bunsen',
    description:
      'Cesium is a soft, gold-colored, alkali metal that is highly reactive and used in atomic clocks.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Cesium.jpg/120px-Cesium.jpg',
    color: '#57178f',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 55,
      neutrons: 78,
      electrons: 55,
      electronShells: [2, 8, 18, 18, 8, 1],
    },
    uses: ['Atomic clocks', 'Photoelectric cells'],
    compounds: [],
  },
  // Barium
  {
    id: 56,
    element: 'Ba',
    name: 'Barium',
    atomicNumber: 56,
    atomicWeight: 137.327,
    group: 2,
    period: 6,
    block: 's',
    electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2',
    electronegativity: 0.89,
    atomicRadius: 222,
    ionizationEnergy: 502.9,
    meltingPoint: 1000,
    boilingPoint: 2170,
    density: 3.62,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    description:
      'Barium is a soft, silvery alkaline earth metal used in fireworks and medical imaging.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Barium-2.jpg/120px-Barium-2.jpg',
    color: '#00C900',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 56,
      neutrons: 81,
      electrons: 56,
      electronShells: [2, 8, 18, 18, 8, 2],
    },
    uses: ['Fireworks', 'Medical imaging'],
    compounds: [],
  },
  // Lanthanum
  {
    id: 57,
    element: 'La',
    name: 'Lanthanum',
    atomicNumber: 57,
    atomicWeight: 138.905,
    group: 3,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1',
    electronegativity: 1.1,
    atomicRadius: 187,
    ionizationEnergy: 538.1,
    meltingPoint: 1193,
    boilingPoint: 3737,
    density: 6.15,
    yearDiscovered: 1839,
    discoveredBy: 'Carl Gustaf Mosander',
    description:
      'Lanthanum is a soft, ductile, silvery-white metal used in camera lenses and batteries.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Lanthanum.jpg/120px-Lanthanum.jpg',
    color: '#70D4FF',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 57,
      neutrons: 82,
      electrons: 57,
      electronShells: [2, 8, 18, 18, 9, 2],
    },
    uses: ['Camera lenses', 'Batteries'],
    compounds: [],
  },
  // Cerium
  {
    id: 58,
    element: 'Ce',
    name: 'Cerium',
    atomicNumber: 58,
    atomicWeight: 140.116,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f1 5d1',
    electronegativity: 1.12,
    atomicRadius: 182,
    ionizationEnergy: 534.4,
    meltingPoint: 1068,
    boilingPoint: 3716,
    density: 6.77,
    yearDiscovered: 1803,
    discoveredBy: 'Jöns Jakob Berzelius',
    description:
      'Cerium is a soft, silvery, ductile metal used in catalytic converters and glass polishing.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cerium.jpg/120px-Cerium.jpg',
    color: '#FFFFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 58,
      neutrons: 82,
      electrons: 58,
      electronShells: [2, 8, 18, 19, 9, 2],
    },
    uses: ['Catalytic converters', 'Glass polishing'],
    compounds: [],
  },
  // Praseodymium
  {
    id: 59,
    element: 'Pr',
    name: 'Praseodymium',
    atomicNumber: 59,
    atomicWeight: 140.908,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f3',
    electronegativity: 1.13,
    atomicRadius: 182,
    ionizationEnergy: 527,
    meltingPoint: 1208,
    boilingPoint: 3793,
    density: 6.77,
    yearDiscovered: 1885,
    discoveredBy: 'Carl Auer von Welsbach',
    description:
      'Praseodymium is a soft, silvery, malleable metal used in magnets and glass coloring.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Praseodymium.jpg/120px-Praseodymium.jpg',
    color: '#D9FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 59,
      neutrons: 82,
      electrons: 59,
      electronShells: [2, 8, 18, 21, 8, 2],
    },
    uses: ['Magnets', 'Glass coloring'],
    compounds: [],
  },
  // Neodymium
  {
    id: 60,
    element: 'Nd',
    name: 'Neodymium',
    atomicNumber: 60,
    atomicWeight: 144.242,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f4',
    electronegativity: 1.14,
    atomicRadius: 181,
    ionizationEnergy: 533.1,
    meltingPoint: 1297,
    boilingPoint: 3347,
    density: 7.01,
    yearDiscovered: 1885,
    discoveredBy: 'Carl Auer von Welsbach',
    description:
      'Neodymium is a soft, silvery metal used in powerful magnets and lasers.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Neodymium.jpg/120px-Neodymium.jpg',
    color: '#C7FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 60,
      neutrons: 84,
      electrons: 60,
      electronShells: [2, 8, 18, 22, 8, 2],
    },
    uses: ['Magnets', 'Lasers'],
    compounds: [],
  },
  // Promethium
  {
    id: 61,
    element: 'Pm',
    name: 'Promethium',
    atomicNumber: 61,
    atomicWeight: 145,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f5',
    electronegativity: null,
    atomicRadius: 183,
    ionizationEnergy: 540,
    meltingPoint: 1315,
    boilingPoint: 3273,
    density: 7.26,
    yearDiscovered: 1945,
    discoveredBy: 'Jacob A. Marinsky',
    description:
      'Promethium is a radioactive, rare earth metal used in luminous paint and atomic batteries.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Promethium.jpg/120px-Promethium.jpg',
    color: '#A3FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 61,
      neutrons: 84,
      electrons: 61,
      electronShells: [2, 8, 18, 23, 8, 2],
    },
    uses: ['Luminous paint', 'Atomic batteries'],
    compounds: [],
  },
  // Samarium
  {
    id: 62,
    element: 'Sm',
    name: 'Samarium',
    atomicNumber: 62,
    atomicWeight: 150.36,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f6',
    electronegativity: 1.17,
    atomicRadius: 180,
    ionizationEnergy: 544.5,
    meltingPoint: 1345,
    boilingPoint: 2067,
    density: 7.52,
    yearDiscovered: 1879,
    discoveredBy: 'Paul Émile Lecoq de Boisbaudran',
    description:
      'Samarium is a rare earth metal used in magnets, lasers, and nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Samarium.jpg/120px-Samarium.jpg',
    color: '#8FFFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 62,
      neutrons: 88,
      electrons: 62,
      electronShells: [2, 8, 18, 24, 8, 2],
    },
    uses: ['Magnets', 'Lasers', 'Nuclear reactors'],
    compounds: [],
  },
  // Europium
  {
    id: 63,
    element: 'Eu',
    name: 'Europium',
    atomicNumber: 63,
    atomicWeight: 151.964,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7',
    electronegativity: null,
    atomicRadius: 199,
    ionizationEnergy: 547.1,
    meltingPoint: 1099,
    boilingPoint: 1802,
    density: 5.24,
    yearDiscovered: 1901,
    discoveredBy: 'Eugène-Anatole Demarçay',
    description:
      'Europium is a soft, silvery metal used in phosphorescent and fluorescent applications.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Europium.jpg/120px-Europium.jpg',
    color: '#61FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 63,
      neutrons: 89,
      electrons: 63,
      electronShells: [2, 8, 18, 25, 8, 2],
    },
    uses: ['Phosphorescent applications', 'Fluorescent lamps'],
    compounds: [],
  },
  // Gadolinium
  {
    id: 64,
    element: 'Gd',
    name: 'Gadolinium',
    atomicNumber: 64,
    atomicWeight: 157.25,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7 5d1',
    electronegativity: 1.2,
    atomicRadius: 180,
    ionizationEnergy: 593.4,
    meltingPoint: 1585,
    boilingPoint: 3546,
    density: 7.9,
    yearDiscovered: 1880,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    description:
      'Gadolinium is a silvery-white, malleable, and ductile rare earth metal used in MRI contrast agents and electronics.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Gadolinium.jpg/120px-Gadolinium.jpg',
    color: '#45FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 64,
      neutrons: 93,
      electrons: 64,
      electronShells: [2, 8, 18, 25, 9, 2],
    },
    uses: ['MRI contrast agents', 'Electronics'],
    compounds: [],
  },
  // Terbium
  {
    id: 65,
    element: 'Tb',
    name: 'Terbium',
    atomicNumber: 65,
    atomicWeight: 158.925,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f9',
    electronegativity: 1.2,
    atomicRadius: 177,
    ionizationEnergy: 565.8,
    meltingPoint: 1629,
    boilingPoint: 3503,
    density: 8.23,
    yearDiscovered: 1843,
    discoveredBy: 'Carl Gustaf Mosander',
    description:
      'Terbium is a rare earth metal used in green phosphors and solid-state devices.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Terbium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Terbium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#30FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 65,
      neutrons: 94,
      electrons: 65,
      electronShells: [2, 8, 18, 27, 8, 2],
    },
    uses: ['Green phosphors', 'Solid-state devices'],
    compounds: [],
  },
  // Dysprosium
  {
    id: 66,
    element: 'Dy',
    name: 'Dysprosium',
    atomicNumber: 66,
    atomicWeight: 162.5,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f10',
    electronegativity: 1.22,
    atomicRadius: 178,
    ionizationEnergy: 573,
    meltingPoint: 1680,
    boilingPoint: 2840,
    density: 8.54,
    yearDiscovered: 1886,
    discoveredBy: 'Paul Émile Lecoq de Boisbaudran',
    description: 'Dysprosium is used in magnets, lasers, and nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Dysprosium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Dysprosium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#1FFFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 66,
      neutrons: 97,
      electrons: 66,
      electronShells: [2, 8, 18, 28, 8, 2],
    },
    uses: ['Magnets', 'Lasers', 'Nuclear reactors'],
    compounds: [],
  },
  // Holmium
  {
    id: 67,
    element: 'Ho',
    name: 'Holmium',
    atomicNumber: 67,
    atomicWeight: 164.93,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f11',
    electronegativity: 1.23,
    atomicRadius: 176,
    ionizationEnergy: 581,
    meltingPoint: 1734,
    boilingPoint: 2973,
    density: 8.8,
    yearDiscovered: 1878,
    discoveredBy: 'Per Teodor Cleve',
    description: 'Holmium is used in nuclear reactors and solid-state lasers.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Holmium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Holmium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#00FFC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 67,
      neutrons: 98,
      electrons: 67,
      electronShells: [2, 8, 18, 29, 8, 2],
    },
    uses: ['Nuclear reactors', 'Solid-state lasers'],
    compounds: [],
  },
  // Erbium
  {
    id: 68,
    element: 'Er',
    name: 'Erbium',
    atomicNumber: 68,
    atomicWeight: 167.26,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f12',
    electronegativity: 1.24,
    atomicRadius: 175,
    ionizationEnergy: 589.3,
    meltingPoint: 1802,
    boilingPoint: 3141,
    density: 9.07,
    yearDiscovered: 1843,
    discoveredBy: 'Carl Gustaf Mosander',
    description: 'Erbium is used in fiber optics and lasers.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Erbium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Erbium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#00E6C7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 68,
      neutrons: 99,
      electrons: 68,
      electronShells: [2, 8, 18, 30, 8, 2],
    },
    uses: ['Fiber optics', 'Lasers'],
    compounds: [],
  },
  // Thulium
  {
    id: 69,
    element: 'Tm',
    name: 'Thulium',
    atomicNumber: 69,
    atomicWeight: 168.93,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f13',
    electronegativity: 1.25,
    atomicRadius: 174,
    ionizationEnergy: 596.7,
    meltingPoint: 1818,
    boilingPoint: 2223,
    density: 9.32,
    yearDiscovered: 1879,
    discoveredBy: 'Per Teodor Cleve',
    description: 'Thulium is used in portable X-ray devices.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Thulium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Thulium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#00C7C7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 69,
      neutrons: 100,
      electrons: 69,
      electronShells: [2, 8, 18, 31, 8, 2],
    },
    uses: ['Portable X-ray devices'],
    compounds: [],
  },
  // Ytterbium
  {
    id: 70,
    element: 'Yb',
    name: 'Ytterbium',
    atomicNumber: 70,
    atomicWeight: 173.05,
    group: null,
    period: 6,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14',
    electronegativity: 1.1,
    atomicRadius: 173,
    ionizationEnergy: 603.4,
    meltingPoint: 1097,
    boilingPoint: 1469,
    density: 6.9,
    yearDiscovered: 1878,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    description:
      'Ytterbium is used in certain steels and as a doping agent in fiber optics.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Ytterbium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Ytterbium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#00A3C7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 70,
      neutrons: 103,
      electrons: 70,
      electronShells: [2, 8, 18, 32, 8, 2],
    },
    uses: ['Steels', 'Fiber optics'],
    compounds: [],
  },
  // Lutetium
  {
    id: 71,
    element: 'Lu',
    name: 'Lutetium',
    atomicNumber: 71,
    atomicWeight: 174.97,
    group: 3,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d1',
    electronegativity: 1.27,
    atomicRadius: 172,
    ionizationEnergy: 523.5,
    meltingPoint: 1663,
    boilingPoint: 3402,
    density: 9.84,
    yearDiscovered: 1907,
    discoveredBy: 'Georges Urbain',
    description: 'Lutetium is used in PET scan detectors and catalysts.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Lutetium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Lutetium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#007FC7',
    state: 'solid',
    classification: 'lanthanide',
    atomicStructure: {
      protons: 71,
      neutrons: 104,
      electrons: 71,
      electronShells: [2, 8, 18, 32, 9, 2],
    },
    uses: ['PET scan detectors', 'Catalysts'],
    compounds: [],
  },
  // Hafnium
  {
    id: 72,
    element: 'Hf',
    name: 'Hafnium',
    atomicNumber: 72,
    atomicWeight: 178.49,
    group: 4,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d2',
    electronegativity: 1.3,
    atomicRadius: 159,
    ionizationEnergy: 658.5,
    meltingPoint: 2506,
    boilingPoint: 4876,
    density: 13.31,
    yearDiscovered: 1923,
    discoveredBy: 'Dirk Coster and George de Hevesy',
    description: 'Hafnium is used in control rods for nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Hafnium_sublimed_dendritic_and_1cm3_cube.jpg/120px-Hafnium_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#0063C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 72,
      neutrons: 106,
      electrons: 72,
      electronShells: [2, 8, 18, 32, 10, 2],
    },
    uses: ['Nuclear reactor control rods'],
    compounds: [],
  },
  // Tantalum
  {
    id: 73,
    element: 'Ta',
    name: 'Tantalum',
    atomicNumber: 73,
    atomicWeight: 180.95,
    group: 5,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d3',
    electronegativity: 1.5,
    atomicRadius: 146,
    ionizationEnergy: 761,
    meltingPoint: 3290,
    boilingPoint: 5731,
    density: 16.69,
    yearDiscovered: 1802,
    discoveredBy: 'Anders Gustaf Ekeberg',
    description: 'Tantalum is used in capacitors and surgical equipment.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tantalum_sublimed_dendritic_and_1cm3_cube.jpg/120px-Tantalum_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#0050C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 73,
      neutrons: 108,
      electrons: 73,
      electronShells: [2, 8, 18, 32, 11, 2],
    },
    uses: ['Capacitors', 'Surgical equipment'],
    compounds: [],
  },
  // Tungsten
  {
    id: 74,
    element: 'W',
    name: 'Tungsten',
    atomicNumber: 74,
    atomicWeight: 183.84,
    group: 6,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d4',
    electronegativity: 2.36,
    atomicRadius: 139,
    ionizationEnergy: 770,
    meltingPoint: 3695,
    boilingPoint: 5828,
    density: 19.25,
    yearDiscovered: 1783,
    discoveredBy: 'Juan José and Fausto Elhuyar',
    description: 'Tungsten is used in light bulb filaments and cutting tools.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tungsten_sublimed_dendritic_and_1cm3_cube.jpg/120px-Tungsten_sublimed_dendritic_and_1cm3_cube.jpg',
    color: '#0037C7',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 74,
      neutrons: 110,
      electrons: 74,
      electronShells: [2, 8, 18, 32, 12, 2],
    },
    uses: ['Light bulb filaments', 'Cutting tools'],
    compounds: [],
  },
  // Rhenium
  {
    id: 75,
    element: 'Re',
    name: 'Rhenium',
    atomicNumber: 75,
    atomicWeight: 186.21,
    group: 7,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d5',
    electronegativity: 1.9,
    atomicRadius: 137,
    ionizationEnergy: 760,
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 21.02,
    yearDiscovered: 1925,
    discoveredBy: 'Walter Noddack, Ida Tacke, Otto Berg',
    description:
      'Rhenium is used in high-temperature superalloys and catalysts.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Rhenium_powder.jpg/120px-Rhenium_powder.jpg',
    color: '#267DAB',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 75,
      neutrons: 111,
      electrons: 75,
      electronShells: [2, 8, 18, 32, 13, 2],
    },
    uses: ['Superalloys', 'Catalysts'],
    compounds: [],
  },
  // Osmium
  {
    id: 76,
    element: 'Os',
    name: 'Osmium',
    atomicNumber: 76,
    atomicWeight: 190.23,
    group: 8,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d6',
    electronegativity: 2.2,
    atomicRadius: 135,
    ionizationEnergy: 840,
    meltingPoint: 3306,
    boilingPoint: 5285,
    density: 22.59,
    yearDiscovered: 1803,
    discoveredBy: 'Smithson Tennant',
    description:
      'Osmium is the densest naturally occurring element and is used in fountain pen tips and electrical contacts.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Osmium_crystals.jpg/120px-Osmium_crystals.jpg',
    color: '#266696',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 76,
      neutrons: 114,
      electrons: 76,
      electronShells: [2, 8, 18, 32, 14, 2],
    },
    uses: ['Fountain pen tips', 'Electrical contacts'],
    compounds: [],
  },
  // Iridium
  {
    id: 77,
    element: 'Ir',
    name: 'Iridium',
    atomicNumber: 77,
    atomicWeight: 192.22,
    group: 9,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d7',
    electronegativity: 2.2,
    atomicRadius: 136,
    ionizationEnergy: 880,
    meltingPoint: 2719,
    boilingPoint: 4701,
    density: 22.56,
    yearDiscovered: 1803,
    discoveredBy: 'Smithson Tennant',
    description:
      'Iridium is used in spark plugs, crucibles, and electrical contacts.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Iridium_powder.jpg/120px-Iridium_powder.jpg',
    color: '#266696',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 77,
      neutrons: 115,
      electrons: 77,
      electronShells: [2, 8, 18, 32, 15, 2],
    },
    uses: ['Spark plugs', 'Crucibles', 'Electrical contacts'],
    compounds: [],
  },
  // Platinum
  {
    id: 78,
    element: 'Pt',
    name: 'Platinum',
    atomicNumber: 78,
    atomicWeight: 195.08,
    group: 10,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d9',
    electronegativity: 2.28,
    atomicRadius: 139,
    ionizationEnergy: 870,
    meltingPoint: 2041,
    boilingPoint: 4098,
    density: 21.45,
    yearDiscovered: 1735,
    discoveredBy: 'Antonio de Ulloa',
    description:
      'Platinum is used in jewelry, catalytic converters, and laboratory equipment.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Platinum_powder.jpg/120px-Platinum_powder.jpg',
    color: '#266696',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 78,
      neutrons: 117,
      electrons: 78,
      electronShells: [2, 8, 18, 32, 17, 1],
    },
    uses: ['Jewelry', 'Catalytic converters', 'Laboratory equipment'],
    compounds: [],
  },
  // Gold
  {
    id: 79,
    element: 'Au',
    name: 'Gold',
    atomicNumber: 79,
    atomicWeight: 196.97,
    group: 11,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d10',
    electronegativity: 2.54,
    atomicRadius: 144,
    ionizationEnergy: 890.1,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    density: 19.32,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Gold is a precious metal used in jewelry, electronics, and as a monetary standard.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Gold_crystal.jpg/120px-Gold_crystal.jpg',
    color: '#FFD700',
    state: 'solid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 79,
      neutrons: 118,
      electrons: 79,
      electronShells: [2, 8, 18, 32, 18, 1],
    },
    uses: ['Jewelry', 'Electronics', 'Monetary standard'],
    compounds: [],
  },
  // Mercury
  {
    id: 80,
    element: 'Hg',
    name: 'Mercury',
    atomicNumber: 80,
    atomicWeight: 200.59,
    group: 12,
    period: 6,
    block: 'd',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10',
    electronegativity: 2.0,
    atomicRadius: 151,
    ionizationEnergy: 1007.1,
    meltingPoint: 234.32,
    boilingPoint: 629.88,
    density: 13.534,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Mercury is a liquid metal at room temperature, used in thermometers and barometers.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mercury_element.jpg/120px-Mercury_element.jpg',
    color: '#B8B8D0',
    state: 'liquid',
    classification: 'transition metal',
    atomicStructure: {
      protons: 80,
      neutrons: 121,
      electrons: 80,
      electronShells: [2, 8, 18, 32, 18, 2],
    },
    uses: ['Thermometers', 'Barometers'],
    compounds: [],
  },
  // Thallium
  {
    id: 81,
    element: 'Tl',
    name: 'Thallium',
    atomicNumber: 81,
    atomicWeight: 204.38,
    group: 13,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p1',
    electronegativity: 1.62,
    atomicRadius: 156,
    ionizationEnergy: 589.4,
    meltingPoint: 577,
    boilingPoint: 1746,
    density: 11.85,
    yearDiscovered: 1861,
    discoveredBy: 'William Crookes',
    description: 'Thallium is used in electronics and optical systems.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Thallium_element.jpg/120px-Thallium_element.jpg',
    color: '#A6544D',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 81,
      neutrons: 123,
      electrons: 81,
      electronShells: [2, 8, 18, 32, 18, 3],
    },
    uses: ['Electronics', 'Optical systems'],
    compounds: [],
  },
  // Lead
  {
    id: 82,
    element: 'Pb',
    name: 'Lead',
    atomicNumber: 82,
    atomicWeight: 207.2,
    group: 14,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p2',
    electronegativity: 2.33,
    atomicRadius: 154,
    ionizationEnergy: 715.6,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    density: 11.34,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description:
      'Lead is a heavy metal used in batteries, shielding, and pigments.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Lead_element.jpg/120px-Lead_element.jpg',
    color: '#575961',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 82,
      neutrons: 125,
      electrons: 82,
      electronShells: [2, 8, 18, 32, 18, 4],
    },
    uses: ['Batteries', 'Shielding', 'Pigments'],
    compounds: [],
  },
  // Bismuth
  {
    id: 83,
    element: 'Bi',
    name: 'Bismuth',
    atomicNumber: 83,
    atomicWeight: 208.98,
    group: 15,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p3',
    electronegativity: 2.02,
    atomicRadius: 143,
    ionizationEnergy: 703,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    density: 9.78,
    yearDiscovered: 'Ancient',
    discoveredBy: 'Unknown',
    description: 'Bismuth is used in cosmetics, alloys, and fire detectors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bismuth_element.jpg/120px-Bismuth_element.jpg',
    color: '#9E4FB5',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 83,
      neutrons: 126,
      electrons: 83,
      electronShells: [2, 8, 18, 32, 18, 5],
    },
    uses: ['Cosmetics', 'Alloys', 'Fire detectors'],
    compounds: [],
  },
  // Polonium
  {
    id: 84,
    element: 'Po',
    name: 'Polonium',
    atomicNumber: 84,
    atomicWeight: 209,
    group: 16,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p4',
    electronegativity: 2.0,
    atomicRadius: 135,
    ionizationEnergy: 812.1,
    meltingPoint: 527,
    boilingPoint: 1235,
    density: 9.196,
    yearDiscovered: 1898,
    discoveredBy: 'Marie Curie, Pierre Curie',
    description: 'Polonium is a rare and highly radioactive metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Polonium_element.jpg/120px-Polonium_element.jpg',
    color: '#AB5C00',
    state: 'solid',
    classification: 'post-transition metal',
    atomicStructure: {
      protons: 84,
      neutrons: 125,
      electrons: 84,
      electronShells: [2, 8, 18, 32, 18, 6],
    },
    uses: ['Antistatic devices', 'Heat sources in space probes'],
    compounds: [],
  },
  // Astatine
  {
    id: 85,
    element: 'At',
    name: 'Astatine',
    atomicNumber: 85,
    atomicWeight: 210,
    group: 17,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p5',
    electronegativity: 2.2,
    atomicRadius: 127,
    ionizationEnergy: 920,
    meltingPoint: 575,
    boilingPoint: 610,
    density: 7,
    yearDiscovered: 1940,
    discoveredBy: 'Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè',
    description: 'Astatine is a rare and radioactive halogen.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Astatine_element.jpg/120px-Astatine_element.jpg',
    color: '#754F45',
    state: 'solid',
    classification: 'halogen',
    atomicStructure: {
      protons: 85,
      neutrons: 125,
      electrons: 85,
      electronShells: [2, 8, 18, 32, 18, 7],
    },
    uses: ['Cancer treatment'],
    compounds: [],
  },
  // Radon
  {
    id: 86,
    element: 'Rn',
    name: 'Radon',
    atomicNumber: 86,
    atomicWeight: 222,
    group: 18,
    period: 6,
    block: 'p',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6',
    electronegativity: null,
    atomicRadius: 120,
    ionizationEnergy: 1037,
    meltingPoint: 202,
    boilingPoint: 211.3,
    density: 9.73,
    yearDiscovered: 1900,
    discoveredBy: 'Friedrich Ernst Dorn',
    description: 'Radon is a radioactive noble gas.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Radon_element.jpg/120px-Radon_element.jpg',
    color: '#428296',
    state: 'gas',
    classification: 'noble gas',
    atomicStructure: {
      protons: 86,
      neutrons: 136,
      electrons: 86,
      electronShells: [2, 8, 18, 32, 18, 8],
    },
    uses: ['Cancer therapy'],
    compounds: [],
  },
  // Francium
  {
    id: 87,
    element: 'Fr',
    name: 'Francium',
    atomicNumber: 87,
    atomicWeight: 223,
    group: 1,
    period: 7,
    block: 's',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s1',
    electronegativity: 0.7,
    atomicRadius: 260,
    ionizationEnergy: 380,
    meltingPoint: 300,
    boilingPoint: 950,
    density: 2.48,
    yearDiscovered: 1939,
    discoveredBy: 'Marguerite Perey',
    description: 'Francium is an extremely rare and radioactive alkali metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Francium_element.jpg/120px-Francium_element.jpg',
    color: '#420066',
    state: 'solid',
    classification: 'alkali metal',
    atomicStructure: {
      protons: 87,
      neutrons: 136,
      electrons: 87,
      electronShells: [2, 8, 18, 32, 18, 8, 1],
    },
    uses: [],
    compounds: [],
  },
  // Radium
  {
    id: 88,
    element: 'Ra',
    name: 'Radium',
    atomicNumber: 88,
    atomicWeight: 226,
    group: 2,
    period: 7,
    block: 's',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2',
    electronegativity: 0.9,
    atomicRadius: 221,
    ionizationEnergy: 509.3,
    meltingPoint: 973,
    boilingPoint: 2010,
    density: 5.5,
    yearDiscovered: 1898,
    discoveredBy: 'Marie Curie, Pierre Curie',
    description: 'Radium is a highly radioactive alkaline earth metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Radium_element.jpg/120px-Radium_element.jpg',
    color: '#007D66',
    state: 'solid',
    classification: 'alkaline earth metal',
    atomicStructure: {
      protons: 88,
      neutrons: 138,
      electrons: 88,
      electronShells: [2, 8, 18, 32, 18, 8, 2],
    },
    uses: ['Radioluminescent paint'],
    compounds: [],
  },
  // Actinium
  {
    id: 89,
    element: 'Ac',
    name: 'Actinium',
    atomicNumber: 89,
    atomicWeight: 227,
    group: 3,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d1',
    electronegativity: 1.1,
    atomicRadius: 215,
    ionizationEnergy: 499,
    meltingPoint: 1323,
    boilingPoint: 3471,
    density: 10.07,
    yearDiscovered: 1899,
    discoveredBy: 'Friedrich Oskar Giesel',
    description: 'Actinium is a soft, silvery-white radioactive metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Actinium_element.jpg/120px-Actinium_element.jpg',
    color: '#70ABFA',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 89,
      neutrons: 138,
      electrons: 89,
      electronShells: [2, 8, 18, 32, 18, 9, 2],
    },
    uses: ['Radiotherapy'],
    compounds: [],
  },
  // Thorium
  {
    id: 90,
    element: 'Th',
    name: 'Thorium',
    atomicNumber: 90,
    atomicWeight: 232.04,
    group: null,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d2',
    electronegativity: 1.3,
    atomicRadius: 206,
    ionizationEnergy: 587,
    meltingPoint: 2023,
    boilingPoint: 5061,
    density: 11.72,
    yearDiscovered: 1828,
    discoveredBy: 'Jöns Jakob Berzelius',
    description:
      'Thorium is a weakly radioactive metal used in nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Thorium_element.jpg/120px-Thorium_element.jpg',
    color: '#00BFFF',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 90,
      neutrons: 142,
      electrons: 90,
      electronShells: [2, 8, 18, 32, 18, 10, 2],
    },
    uses: ['Nuclear reactors'],
    compounds: [],
  },
  // Protactinium
  {
    id: 91,
    element: 'Pa',
    name: 'Protactinium',
    atomicNumber: 91,
    atomicWeight: 231.04,
    group: null,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f2 6d1',
    electronegativity: 1.5,
    atomicRadius: 200,
    ionizationEnergy: 568,
    meltingPoint: 1841,
    boilingPoint: 4300,
    density: 15.37,
    yearDiscovered: 1913,
    discoveredBy: 'Oswald Helmuth Göhring, Kasimir Fajans',
    description: 'Protactinium is a rare and highly radioactive metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Protactinium_element.jpg/120px-Protactinium_element.jpg',
    color: '#00A1FF',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 91,
      neutrons: 140,
      electrons: 91,
      electronShells: [2, 8, 18, 32, 20, 9, 2],
    },
    uses: [],
    compounds: [],
  },
  // Uranium
  {
    id: 92,
    element: 'U',
    name: 'Uranium',
    atomicNumber: 92,
    atomicWeight: 238.03,
    group: null,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f3 6d1',
    electronegativity: 1.38,
    atomicRadius: 196,
    ionizationEnergy: 597.6,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    density: 18.95,
    yearDiscovered: 1789,
    discoveredBy: 'Martin Heinrich Klaproth',
    description:
      'Uranium is a radioactive metal used as fuel in nuclear reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Uranium_element.jpg/120px-Uranium_element.jpg',
    color: '#008FFF',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 92,
      neutrons: 146,
      electrons: 92,
      electronShells: [2, 8, 18, 32, 21, 9, 2],
    },
    uses: ['Nuclear fuel'],
    compounds: [],
  },
  // Neptunium
  {
    id: 93,
    element: 'Np',
    name: 'Neptunium',
    atomicNumber: 93,
    atomicWeight: 237,
    group: null,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f4 6d1',
    electronegativity: 1.36,
    atomicRadius: 190,
    ionizationEnergy: 604.5,
    meltingPoint: 917,
    boilingPoint: 4273,
    density: 20.45,
    yearDiscovered: 1940,
    discoveredBy: 'Edwin McMillan, Philip H. Abelson',
    description: 'Neptunium is a radioactive actinide metal.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Neptunium_element.jpg/120px-Neptunium_element.jpg',
    color: '#0080FF',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 93,
      neutrons: 144,
      electrons: 93,
      electronShells: [2, 8, 18, 32, 22, 9, 2],
    },
    uses: [],
    compounds: [],
  },
  // Plutonium
  {
    id: 94,
    element: 'Pu',
    name: 'Plutonium',
    atomicNumber: 94,
    atomicWeight: 244,
    group: null,
    period: 7,
    block: 'f',
    electronConfiguration:
      '1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f6',
    electronegativity: 1.28,
    atomicRadius: 187,
    ionizationEnergy: 584.7,
    meltingPoint: 912.5,
    boilingPoint: 3505,
    density: 19.86,
    yearDiscovered: 1940,
    discoveredBy:
      'Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl',
    description:
      'Plutonium is a radioactive actinide metal used in nuclear weapons and reactors.',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Plutonium_element.jpg/120px-Plutonium_element.jpg',
    color: '#006BFF',
    state: 'solid',
    classification: 'actinide',
    atomicStructure: {
      protons: 94,
      neutrons: 150,
      electrons: 94,
      electronShells: [2, 8, 18, 32, 24, 8, 2],
    },
    uses: ['Nuclear weapons', 'Nuclear reactors'],
    compounds: [],
  },
];
