// import { element } from 'three/tsl';

// export const data = [
//   {
//     id: 1,
//     element: 'H',
//     name: 'Hydrogen',
//     atomicNumber: 1,
//     atomicWeight: 1.008,
//     group: 1,
//     period: 1,
//     block: 's',
//     electronConfiguration: '1s1',
//     electronegativity: 2.2,
//     atomicRadius: 53,
//     ionizationEnergy: 1312,
//     meltingPoint: 14.01,
//     boilingPoint: 20.28,
//     density: 0.08988,
//     yearDiscovered: 1766,
//     discoveredBy: 'Henry Cavendish',
//     description:
//       'Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless gas at room temperature and is highly flammable. Hydrogen is essential for life and is a key component of water.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Hydrogen-2D-vdW.png/120px-Hydrogen-2D-vdW.png',
//     color: '#FFFFFF',
//     state: 'gas',
//     classification: 'nonmetal',
//     atomicStructure: {
//       protons: 1,
//       neutrons: 0,
//       electrons: 1,
//       electronShells: [1],
//     },
//     isotopes: [
//       {
//         name: 'Protium',
//         symbol: '¹H',
//         massNumber: 1,
//         abundance: 99.98,
//       },
//       {
//         name: 'Deuterium',
//         symbol: '²H',
//         massNumber: 2,
//         abundance: 0.02,
//       },
//       {
//         name: 'Tritium',
//         symbol: '³H',
//         massNumber: 3,
//         abundance: 'trace',
//       },
//     ],
//     about:
//       'Hydrogen is the simplest and most abundant element in the universe, making up about 75% of its elemental mass. It plays a crucial role in the formation of stars and galaxies. Hydrogen is also a key component of water, which is essential for all known forms of life.',

//     uses: [
//       'Fuel cells',
//       'Rocket fuel',
//       'Hydrogenation of fats and oils',
//       'Production of ammonia',
//     ],
//     compounds: [
//       {
//         name: 'Water',
//         formula: 'H2O',
//         uses: ['Essential for life', 'Solvent', 'Industrial processes'],
//       },
//       {
//         name: 'Hydrochloric Acid',
//         formula: 'HCl',
//         uses: ['pH regulation', 'Cleaning agent', 'Food processing'],
//       },
//     ],
//   },
// ];
// {
//     id: 49,
//     element: 'Hf',
//     name: 'Hafnium',
//     atomicNumber: 49,
//     atomicWeight: 178.49,
//     group: 4,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5f2',
//     electronegativity: 1.3,
//     atomicRadius: 175,
//     ionizationEnergy: 659.0,
//     meltingPoint: 2233,
//     boilingPoint: 4603,
//     density: 13.31,
//     yearDiscovered: 1923,
//     discoveredBy: 'Zirconium',
//     description:
//       'Hafnium is a shiny, silvery metal, used in nuclear reactors, and as a getter in vacuum tubes.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Hafnium_crystals.jpg/120px-Hafnium_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 49,
//       neutrons: 76,
//       electrons: 49,
//       electronShells: [2, 8, 18, 32, 2],
//     },
//     uses: ['Nuclear reactors', 'Getter in vacuum tubes'],
//     compounds: [],
//   },
//   // Tantalum
//   {
//     id: 50,
//     element: 'Ta',
//     name: 'Tantalum',
//     atomicNumber: 50,
//     atomicWeight: 180.9479,
//     group: 5,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5f3',
//     electronegativity: 1.5,
//     atomicRadius: 146,
//     ionizationEnergy: 761.0,
//     meltingPoint: 3017,
//     boilingPoint: 5458,
//     density: 16.65,
//     yearDiscovered: 1802,
//     discoveredBy: 'Anders Gustav Ekeberg',
//     description:
//       'Tantalum is a hard, blue-gray metal, used in electronic components, and as a substitute for platinum in some reactions.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tantalum_crystals.jpg/120px-Tantalum_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 50,
//       neutrons: 70,
//       electrons: 50,
//       electronShells: [2, 8, 18, 32, 3],
//     },
//     uses: ['Electronic components', 'Substitute for platinum'],
//     compounds: [],
//   },
//   // Tungsten
//   {
//     id: 51,
//     element: 'W',
//     name: 'Tungsten',
//     atomicNumber: 51,
//     atomicWeight: 183.84,
//     group: 6,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5f4',
//     electronegativity: 2.36,
//     atomicRadius: 139,
//     ionizationEnergy: 770.0,
//     meltingPoint: 3422,
//     boilingPoint: 5555,
//     density: 19.25,
//     yearDiscovered: 1783,
//     discoveredBy: 'Juan José and Fausto Elhuyar',
//     description:
//       'Tungsten is a hard, rare metal, used in light bulb filaments, and as a target material in X-ray tubes.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tungsten_crystals.jpg/120px-Tungsten_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 51,
//       neutrons: 74,
//       electrons: 51,
//       electronShells: [2, 8, 18, 32, 4],
//     },
//     uses: ['Light bulb filaments', 'Target material in X-ray tubes'],
//     compounds: [],
//   },
//   // Rhenium
//   {
//     id: 52,
//     element: 'Re',
//     name: 'Rhenium',
//     atomicNumber: 52,
//     atomicWeight: 186.207,
//     group: 7,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5f5',
//     electronegativity: 1.9,
//     atomicRadius: 139,
//     ionizationEnergy: 760.0,
//     meltingPoint: 3186,
//     boilingPoint: 5869,
//     density: 21.02,
//     yearDiscovered: 1925,
//     discoveredBy: 'Walter Noddack, Ida Tacke, and Otto Berg',
//     description:
//       'Rhenium is a silvery-white, heavy metal, used in high-temperature superalloys, and as a catalyst in petroleum refining.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Rhenium_crystals.jpg/120px-Rhenium_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 52,
//       neutrons: 75,
//       electrons: 52,
//       electronShells: [2, 8, 18, 13, 5],
//     },
//     uses: ['High-temperature superalloys', 'Catalyst in petroleum refining'],
//     compounds: [],
//   },
//   // Osmium
//   {
//     id: 53,
//     element: 'Os',
//     name: 'Osmium',
//     atomicNumber: 53,
//     atomicWeight: 190.23,
//     group: 8,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d6',
//     electronegativity: 2.2,
//     atomicRadius: 138,
//     ionizationEnergy: 840.0,
//     meltingPoint: 3306,
//     boilingPoint: 5285,
//     density: 22.59,
//     yearDiscovered: 1803,
//     discoveredBy: 'William Hyde Wollaston',
//     description:
//       'Osmium is a dense, blue-gray metal, used in fountain pen nibs, electrical contacts, and as a catalyst.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Osmium_crystals.jpg/120px-Osmium_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 53,
//       neutrons: 76,
//       electrons: 53,
//       electronShells: [2, 8, 18, 13, 6],
//     },
//     uses: ['Fountain pen nibs', 'Electrical contacts', 'Catalyst'],
//     compounds: [],
//   },
//   // Iridium
//   {
//     id: 54,
//     element: 'Ir',
//     name: 'Iridium',
//     atomicNumber: 54,
//     atomicWeight: 192.217,
//     group: 9,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d7',
//     electronegativity: 2.2,
//     atomicRadius: 136,
//     ionizationEnergy: 880.0,
//     meltingPoint: 2466,
//     boilingPoint: 4425,
//     density: 22.56,
//     yearDiscovered: 1803,
//     discoveredBy: 'William Hyde Wollaston',
//     description:
//       'Iridium is a very hard, brittle metal, used in high-temperature alloys, electrical contacts, and as a catalyst.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Iridium_crystals.jpg/120px-Iridium_crystals.jpg',
//     color: '#BFC2C7',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 54,
//       neutrons: 77,
//       electrons: 54,
//       electronShells: [2, 8, 18, 13, 7],
//     },
//     uses: ['High-temperature alloys', 'Electrical contacts', 'Catalyst'],
//     compounds: [],
//   },
//   // Platinum
//   {
//     id: 55,
//     element: 'Pt',
//     name: 'Platinum',
//     atomicNumber: 55,
//     atomicWeight: 195.084,
//     group: 10,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10',
//     electronegativity: 2.28,
//     atomicRadius: 139,
//     ionizationEnergy: 870.0,
//     meltingPoint: 1768.6,
//     boilingPoint: 3825,
//     density: 21.45,
//     yearDiscovered: 'Ancient',
//     discoveredBy: 'Unknown',
//     description:
//       'Platinum is a dense, malleable, and ductile metal, used in jewelry, catalytic converters, and electrical contacts.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Platinum_crystals.jpg/120px-Platinum_crystals.jpg',
//     color: '#C0C0C0',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 78,
//       neutrons: 117,
//       electrons: 78,
//       electronShells: [2, 8, 18, 32, 17, 1],
//     },
//     uses: ['Jewelry', 'Catalytic converters', 'Electrical contacts'],
//     compounds: [],
//   },
//   // Gold
//   {
//     id: 56,
//     element: 'Au',
//     name: 'Gold',
//     atomicNumber: 56,
//     atomicWeight: 196.9665,
//     group: 11,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 5d10',
//     electronegativity: 2.54,
//     atomicRadius: 144,
//     ionizationEnergy: 890.0,
//     meltingPoint: 1064.18,
//     boilingPoint: 2856,
//     density: 19.32,
//     yearDiscovered: 'Ancient',
//     discoveredBy: 'Unknown',
//     description:
//       'Gold is a yellow, dense metal, highly valued for jewelry, coins, and as a standard for monetary systems.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Gold_crystals.jpg/120px-Gold_crystals.jpg',
//     color: '#FFD700',
//     state: 'solid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 79,
//       neutrons: 118,
//       electrons: 79,
//       electronShells: [2, 8, 18, 32, 18, 1],
//     },
//     uses: ['Jewelry', 'Coins', 'Electronics', 'Dentistry'],
//     compounds: [],
//   },
//   // Mercury
//   {
//     id: 57,
//     element: 'Hg',
//     name: 'Mercury',
//     atomicNumber: 57,
//     atomicWeight: 200.592,
//     group: 12,
//     period: 6,
//     block: 'd',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 5d10 6s2',
//     electronegativity: 2.0,
//     atomicRadius: 155,
//     ionizationEnergy: 1007.1,
//     meltingPoint: -38.83,
//     boilingPoint: 356.73,
//     density: 13.534,
//     yearDiscovered: 'Ancient',
//     discoveredBy: 'Unknown',
//     description:
//       'Mercury is a heavy, silvery-white liquid metal, used in thermometers, barometers, and as a preservative in vaccines.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Mercury_crystals.jpg/120px-Mercury_crystals.jpg',
//     color: '#BFBFBF',
//     state: 'liquid',
//     classification: 'transition metal',
//     atomicStructure: {
//       protons: 80,
//       neutrons: 121,
//       electrons: 80,
//       electronShells: [2, 8, 18, 32, 18, 2],
//     },
//     uses: ['Thermometers', 'Barometers', 'Vaccines'],
//     compounds: [],
//   },
//   // Thallium
//   {
//     id: 58,
//     element: 'Tl',
//     name: 'Thallium',
//     atomicNumber: 58,
//     atomicWeight: 204.38,
//     group: 13,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p1',
//     electronegativity: 1.54,
//     atomicRadius: 156,
//     ionizationEnergy: 589.0,
//     meltingPoint: 304,
//     boilingPoint: 1470,
//     density: 11.85,
//     yearDiscovered: 1861,
//     discoveredBy: 'William Crookes',
//     description:
//       'Thallium is a soft, malleable metal, used in electronics, glass, and as a poison.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Thallium_crystals.jpg/120px-Thallium_crystals.jpg',
//     color: '#A6A6AB',
//     state: 'solid',
//     classification: 'post-transition metal',
//     atomicStructure: {
//       protons: 81,
//       neutrons: 123,
//       electrons: 81,
//       electronShells: [2, 8, 18, 32, 18, 3],
//     },
//     uses: ['Electronics', 'Glass', 'Poison'],
//     compounds: [],
//   },
//   // Lead
//   {
//     id: 59,
//     element: 'Pb',
//     name: 'Lead',
//     atomicNumber: 59,
//     atomicWeight: 207.2,
//     group: 14,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p2',
//     electronegativity: 1.87,
//     atomicRadius: 174,
//     ionizationEnergy: 715.0,
//     meltingPoint: 327.46,
//     boilingPoint: 1749,
//     density: 11.343,
//     yearDiscovered: 'Ancient',
//     discoveredBy: 'Unknown',
//     description:
//       'Lead is a heavy, malleable metal, used in batteries, radiation shielding, and as a pigment in paints.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Lead_crystals.jpg/120px-Lead_crystals.jpg',
//     color: '#404040',
//     state: 'solid',
//     classification: 'post-transition metal',
//     atomicStructure: {
//       protons: 82,
//       neutrons: 125,
//       electrons: 82,
//       electronShells: [2, 8, 18, 32, 18, 4],
//     },
//     uses: ['Batteries', 'Radiation shielding', 'Pigment in paints'],
//     compounds: [],
//   },
//   // Bismuth
//   {
//     id: 60,
//     element: 'Bi',
//     name: 'Bismuth',
//     atomicNumber: 60,
//     atomicWeight: 208.9804,
//     group: 15,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p3',
//     electronegativity: 2.02,
//     atomicRadius: 167,
//     ionizationEnergy: 703.0,
//     meltingPoint: 271.4,
//     boilingPoint: 1564,
//     density: 9.78,
//     yearDiscovered: 1753,
//     discoveredBy: 'Claude Louis Berthollet',
//     description:
//       'Bismuth is a brittle, crystalline metal, used in cosmetics, pigments, and as a replacement for lead in some applications.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bismuth_crystals.jpg/120px-Bismuth_crystals.jpg',
//     color: '#C8C8C8',
//     state: 'solid',
//     classification: 'post-transition metal',
//     atomicStructure: {
//       protons: 83,
//       neutrons: 125,
//       electrons: 83,
//       electronShells: [2, 8, 18, 32, 18, 5],
//     },
//     uses: ['Cosmetics', 'Pigments', 'Lead replacement'],
//     compounds: [],
//   },
//   // Polonium
//   {
//     id: 61,
//     element: 'Po',
//     name: 'Polonium',
//     atomicNumber: 61,
//     atomicWeight: 209,
//     group: 16,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p4',
//     electronegativity: 2.0,
//     atomicRadius: 140,
//     ionizationEnergy: 812.0,
//     meltingPoint: 254,
//     boilingPoint: 962,
//     density: 9.196,
//     yearDiscovered: 1940,
//     discoveredBy: 'Glenn T. Seaborg, Emilio Segrè, and Albert Ghiorso',
//     description:
//       'Polonium is a highly radioactive, silvery metal, used as a heat source in space equipment and as a poison.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Polonium_crystals.jpg/120px-Polonium_crystals.jpg',
//     color: '#A0A0A0',
//     state: 'solid',
//     classification: 'metalloid',
//     atomicStructure: {
//       protons: 84,
//       neutrons: 125,
//       electrons: 84,
//       electronShells: [2, 8, 18, 32, 18, 6],
//     },
//     uses: ['Heat source in space equipment', 'Poison'],
//     compounds: [],
//   },
//   // Astatine
//   {
//     id: 62,
//     element: 'At',
//     name: 'Astatine',
//     atomicNumber: 62,
//     atomicWeight: 210,
//     group: 17,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p5',
//     electronegativity: 2.2,
//     atomicRadius: 202,
//     ionizationEnergy: 920.0,
//     meltingPoint: 302,
//     boilingPoint: 337,
//     density: 7.0,
//     yearDiscovered: 1940,
//     discoveredBy: 'Dale R. Corson, Emilio Segrè, and Glenn T. Seaborg',
//     description:
//       'Astatine is a rare, radioactive halogen, used in some cancer treatments and as a tracer in biomedical research.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Astatine_crystals.jpg/120px-Astatine_crystals.jpg',
//     color: '#7F7F7F',
//     state: 'solid',
//     classification: 'halogen',
//     atomicStructure: {
//       protons: 85,
//       neutrons: 125,
//       electrons: 85,
//       electronShells: [2, 8, 18, 32, 18, 7],
//     },
//     uses: ['Cancer treatment', 'Tracer in biomedical research'],
//     compounds: [],
//   },
//   // Radon
//   {
//     id: 63,
//     element: 'Rn',
//     name: 'Radon',
//     atomicNumber: 63,
//     atomicWeight: 222,
//     group: 18,
//     period: 6,
//     block: 'p',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 6p6',
//     electronegativity: null,
//     atomicRadius: 120,
//     ionizationEnergy: 1037.0,
//     meltingPoint: -71,
//     boilingPoint: -61.7,
//     density: 0.00973,
//     yearDiscovered: 1900,
//     discoveredBy: 'Frederick William Aston',
//     description:
//       'Radon is a colorless, odorless, tasteless noble gas, highly radioactive, and used in some cancer therapies.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Radon_crystals.jpg/120px-Radon_crystals.jpg',
//     color: '#B3E3F5',
//     state: 'gas',
//     classification: 'noble gas',
//     atomicStructure: {
//       protons: 86,
//       neutrons: 136,
//       electrons: 86,
//       electronShells: [2, 8, 18, 32, 18, 8],
//     },
//     uses: ['Cancer therapies', 'Radiation shielding'],
//     compounds: [],
//   },
//   // Francium
//   {
//     id: 64,
//     element: 'Fr',
//     name: 'Francium',
//     atomicNumber: 64,
//     atomicWeight: 223,
//     group: 1,
//     period: 7,
//     block: 's',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2 6p6 7s1',
//     electronegativity: 0.7,
//     atomicRadius: 270,
//     ionizationEnergy: 378.0,
//     meltingPoint: 27,
//     boilingPoint: 677,
//     density: 1.87,
//     yearDiscovered: 1939,
//     discoveredBy: 'Marguerite Perey',
//     description:
//       'Francium is a highly radioactive, alkali metal, and is the least stable of the first 101 elements.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Francium_crystals.jpg/120px-Francium_crystals.jpg',
//     color: '#A24AFC',
//     state: 'solid',
//     classification: 'alkali metal',
//     atomicStructure: {
//       protons: 87,
//       neutrons: 136,
//       electrons: 87,
//       electronShells: [2, 8, 18, 32, 18, 8, 1],
//     },
//     uses: ['Research', 'Radiation sources'],
//     compounds: [],
//   },
//   // Radium
//   {
//     id: 65,
//     element: 'Ra',
//     name: 'Radium',
//     atomicNumber: 65,
//     atomicWeight: 226,
//     group: 2,
//     period: 7,
//     block: 's',
//     electronConfiguration: '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2 6p6 7s2',
//     electronegativity: 0.9,
//     atomicRadius: 215,
//     ionizationEnergy: 1419.0,
//     meltingPoint: 700,
//     boilingPoint: 1413,
//     density: 5.5,
//     yearDiscovered: 1898,
//     discoveredBy: 'Marie Curie and Pierre Curie',
//     description:
//       'Radium is a highly radioactive, silvery-white metal, used in radiotherapy for cancer treatment.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Radium_crystals.jpg/120px-Radium_crystals.jpg',
//     color: '#C0C0C0',
//     state: 'solid',
//     classification: 'alkaline earth metal',
//     atomicStructure: {
//       protons: 88,
//       neutrons: 138,
//       electrons: 88,
//       electronShells: [2, 8, 18, 32, 18, 8, 2],
//     },
//     uses: ['Radiotherapy', 'Luminous paints'],
//     compounds: [],
//   },
//   // Actinium
//   {
//     id: 66,
//     element: 'Ac',
//     name: 'Actinium',
//     atomicNumber: 66,
//     atomicWeight: 227,
//     group: 3,
//     period: 7,
//     block: 'f',
//     electronConfiguration:
//       '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2 6p6 7s2 5f1',
//     electronegativity: 1.1,
//     atomicRadius: 180,
//     ionizationEnergy: 1050.0,
//     meltingPoint: 1050,
//     boilingPoint: 1500,
//     density: 10.07,
//     yearDiscovered: 1899,
//     discoveredBy: 'Friedrich Oskar Giesel',
//     description:
//       'Actinium is a soft, silvery-white, radioactive metal, used as a neutron source and in radiation therapy.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Actinium_crystals.jpg/120px-Actinium_crystals.jpg',
//     color: '#C0C0C0',
//     state: 'solid',
//     classification: 'actinide',
//     atomicStructure: {
//       protons: 89,
//       neutrons: 138,
//       electrons: 89,
//       electronShells: [2, 8, 18, 32, 18, 8, 3],
//     },
//     uses: ['Neutron source', 'Radiation therapy'],
//     compounds: [],
//   },
//   // Thorium
//   {
//     id: 67,
//     element: 'Th',
//     name: 'Thorium',
//     atomicNumber: 67,
//     atomicWeight: 232.038,
//     group: 4,
//     period: 7,
//     block: 'f',
//     electronConfiguration:
//       '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2 6p6 7s2 5f2',
//     electronegativity: 1.3,
//     atomicRadius: 175,
//     ionizationEnergy: 587.0,
//     meltingPoint: 1750,
//     boilingPoint: 4780,
//     density: 11.724,
//     yearDiscovered: 1828,
//     discoveredBy: 'Jöns Jacob Berzelius',
//     description:
//       'Thorium is a silvery-white, radioactive metal, used as a fuel in nuclear reactors and in some alloys.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Thorium_crystals.jpg/120px-Thorium_crystals.jpg',
//     color: '#C0C0C0',
//     state: 'solid',
//     classification: 'actinide',
//     atomicStructure: {
//       protons: 90,
//       neutrons: 142,
//       electrons: 90,
//       electronShells: [2, 8, 18, 32, 18, 8, 4],
//     },
//     uses: ['Nuclear fuel', 'Alloys'],
//     compounds: [],
//   },
//   // Protactinium
//   {
//     id: 68,
//     element: 'Pa',
//     name: 'Protactinium',
//     atomicNumber: 68,
//     atomicWeight: 231.0359,
//     group: 5,
//     period: 7,
//     block: 'f',
//     electronConfiguration:
//       '1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2 6p6 7s2 5f3',
//     electronegativity: 1.5,
//     atomicRadius: 180,
//     ionizationEnergy: 1050.0,
//     meltingPoint: 1050,
//     boilingPoint: 1500,
//     density: 15.37,
//     yearDiscovered: 1940,
//     discoveredBy: 'Glenn T. Seaborg, Emilio Segrè, and Albert Ghiorso',
//     description:
//       'Protactinium is a dense, silvery-gray, radioactive metal, used in nuclear reactors and as a catalyst in organic synthesis.',
//     image:
//       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Protactinium_crystals.jpg/120px-Protactinium_crystals.jpg',
//     color: '#C0C0C0',
//     state: 'solid',
//     classification: 'actinide',
//     atomicStructure: {
//       protons: 91,
//       neutrons: 140,
//       electrons: 91,
//       electronShells: [2, 8, 18, 32, 18, 8, 5],
//     },
//     uses: ['Nuclear reactors', 'Catalyst in organic synthesis'],
//     compounds: [],
//   },
